-- SUPERSEDED same day (2026-07-29) — DO NOT APPLY.
--
-- First cut put email locking on the D1 join-code row (a CRM mint-time preset). That
-- was the wrong end of the funnel: the email at stake belongs to whoever redeems the
-- join code on the landing page, so the lock choice is theirs, at redeem time — it now
-- rides `POST /api/join` as `email_locked: true` (a checkbox on the join page's invite
-- mode), and no code-row column is involved. See agents.d/modules/join.md § "Per-redemption
-- Discourse invites".
--
-- History: the ALTER below ran on the PREVIEW database only, before the rethink. The
-- column sits there dormant and unread — harmless. Prod was never migrated and must
-- not be; this file stays to explain the preview/prod schema difference.
--
-- ALTER TABLE invite_codes ADD COLUMN email_locked INTEGER NOT NULL DEFAULT 0;
